services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    environment:
      - ENVIRONMENT=development
    depends_on:
      scylla:
        condition: service_healthy

  scylla_db:
    image: scylladb/scylla:latest
    container_name: scylla_db
    ports:
      - "9042:9042" # CQL
      - "9160:9160" # Native Transport
      - "10000:10000" # REST API port
    volumes:
      - scylla_data:/var/lib/scylladb
    environment:
      - SCYLLA_DEVELOPER_MODE=1
    command: --smp 1 --memory 2G --overprovisioned 1 # 컨테이너 메모리 설정
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  scylla_data:
