version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: blueberry-postgres
    environment:
      POSTGRES_DB: blueberry_db
      POSTGRES_USER: blueberry_user
      POSTGRES_PASSWORD: blueberry_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: